### ISSUE TITLE
Adding source for MTA station IDs

### ISSUE THREAD

**Issue by rob-lambeth** [rob718/mta-leavenow#1]
Thanks so much for this! I'm new to Python and R-Pi and have been using mta-leavenow as a first project. It's awesome. All of your explanation comments have been super helpful for a beginner like me who is self-teaching. It's up and running on my mac and I'm hoping to implement traintime mode on a pi with an e-ink display at home.

This isn't actually an *issue*, but the only thing that was missing for me was a reference for station IDs. That's probably somewhere in the MTA dev materials, but for other beginners like me, I found this reference super helpful (and searchable):

https://transitfeeds.com/p/mta/79/latest/stops

Thanks again!

**Comment by rob718** [comment]
Thanks Rob! I've added it to readme.
